name: Pull Request

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Set-up NodeJS
       uses: actions/setup-node@v1
       with:
         node-version: 14.x
     - name: Restore node_modules cache
       uses: actions/cache@v2
       with:
         path: |
           node_modules
           */*/node_modules
         key: ${{ runner.os }}-${{ hashFiles('**/package-lock.lock') }}
     - name: Install dependencies
       run: npm install
     - name: Build the libraries
       run: npm run build
     - name: Run linter
       run: npm run lint
     - name: Run Tests with coverage
       run: npm run test:coverage
     - name: Upload coverage to codecov
       uses: codecov/codecov-action@v1
